
project:
  output-dir: docs

lang: en

website:
  navbar:
    right:
      - href: de
        text: ğŸŒ Auf Deutsch wechseln
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: "About"
  title: "Multi-languages Websites with Quarto!"