
project:
  output-dir: docs/de

lang: de

website:
  navbar:
    right:
      - href: ../
        text: ğŸŒ Switch to English
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: "Infos"
  title: "Mehrsprachige Websiten mit Quarto!"